document.addEventListener("DOMContentLoaded", function() {
    const quotes = [
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
        "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
        "The best way to predict the future is to invent it. - Alan Kay",
        "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
        "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
        "Act as if what you do makes a difference. It does. - William James",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
        "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
        "Success is not in what you have, but who you are. - Bo Bennett",
        "The way to get started is to quit talking and begin doing. - Walt Disney",
        "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "Life is what happens when you're busy making other plans. - John Lennon",
        "Get busy living or get busy dying. - Stephen King",
        "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
        "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
        "No matter what you're going through, there's a light at the end of the tunnel. - Demi Lovato",
        "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome. - William James",
        "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
        "Good, better, best. Never let it rest. 'Til your good is better and your better is best. - St. Jerome",
        "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
        "The most effective way to do it, is to do it. - Amelia Earhart",
        "Act as if what you do makes a difference. It does. - William James",
        "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
        "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
        "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
        "The man who moves a mountain begins by carrying away small stones. - Confucius",
        "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
        "Aim for the moon. If you miss, you may hit a star. - W. Clement Stone",
        "Life is 10% what happens to us and 90% how we react to it. - Dennis P. Kimbro",
        "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
        "When something is important enough, you do it even if the odds are not in your favor. - Elon Musk",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
        "Don't let yesterday take up too much of today. - Will Rogers",
        "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
        "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
        "Whether you think you can or you think you can't, you're right. - Henry Ford",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
        "Your limitation—it's only your imagination. - Unknown",
        "Push yourself, because no one else is going to do it for you. - Unknown",
        "Great things never come from comfort zones. - Unknown",
        "Dream it. Wish it. Do it. - Unknown",
        "Success doesn't just find you. You have to go out and get it. - Unknown",
    ];

    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById("quote").innerText = randomQuote;
});
